### ISSUE TITLE
Please show a number of days env is being taken by person

### ISSUE THREAD

**Issue by serhiiivashchenko** [surg/env-keeper#21]
It would be great to see how many days env is being taken by a person. Then we can make a rule, for example if env is taken more than 3-5 days - automatically release it.

Example: 
​_qa-env_​ is taken by "username" for "x" days.

**Comment by yurylyt** [comment]
while 'automatic' release is rather a controversial feature (e.g. what if the one really needs to hold it for so long?), an indication of days is a good one.

**Comment by yurylyt** [comment]
a date is included into env's status message, so you can judge on a number of days on your own. 
automatic releasing will add more questions than solve issues, hence it will not be implemented. 
You can use '[seize](https://github.com/surg/env-keeper/blob/master/usage.md)' command to forcefully overtake the env. Just be careful with it :)
